public class day2 {

    static String input = "13-15 c: cqbhncccjsncqcc\n" +
            "2-3 v: zvdvfd\n" +
            "9-14 b: rbrbnbbbqdfrht\n" +
            "11-12 k: kkkkkkkkkkxqk\n" +
            "4-5 b: bqbbdm\n" +
            "10-12 w: kwwkwwwrwzzwwwwzwswx\n" +
            "1-11 g: grrmgmqgghw\n" +
            "4-5 m: mbmhmvmwdvxmvpw\n" +
            "1-13 n: ndnnnnnnnnnns\n" +
            "11-18 l: lllllllllllllllllll\n" +
            "4-5 c: cccscc\n" +
            "2-4 k: bkfr\n" +
            "9-13 k: lcmsvkknrxtkkksgvkjg\n" +
            "1-2 b: bhwgb\n" +
            "1-4 j: zjjcjj\n" +
            "7-11 g: nnffggdmggr\n" +
            "3-4 z: zzhzz\n" +
            "4-10 g: mggkgvgggmggkggmqg\n" +
            "4-5 n: dcmnl\n" +
            "11-15 s: gzpdvsmnzsshswzs\n" +
            "10-14 x: xmvpxjtlxxhxtpdhsnx\n" +
            "5-15 v: zzhjdpgxlsvphzv\n" +
            "4-8 k: dsfktqchpkk\n" +
            "6-7 j: jzjgjqld\n" +
            "12-16 r: rrrrrrrrrrrhrrrrhrr\n" +
            "1-2 l: lllllll\n" +
            "2-3 q: jqxwtggmgqmzpljdvkt\n" +
            "8-11 p: xpmcppppwvzp\n" +
            "7-8 c: vwcvkcct\n" +
            "4-10 d: lsmdffzdsrk\n" +
            "2-3 p: sxpg\n" +
            "4-11 p: rzlgxshhpbp\n" +
            "1-4 b: qbbbbbbbbbbb\n" +
            "6-11 m: zwmzmmlbmxgphkks\n" +
            "1-4 n: lnnnn\n" +
            "15-16 h: hhbdmbhchhhkhhrw\n" +
            "10-11 k: kkkqtwkkkkkkkkn\n" +
            "2-13 m: mggmmxmrzmwglbmmm\n" +
            "12-14 g: ggggrggggxgwhggggd\n" +
            "7-11 l: llbqsqlkvll\n" +
            "1-3 f: ffff\n" +
            "4-9 h: qvnhvcmpmfdbqhkdsg\n" +
            "3-8 d: ddsdddddd\n" +
            "14-15 j: qjjjzjjjjjbxmjs\n" +
            "3-5 j: jjjjtctjjjs\n" +
            "12-13 q: qqqqqqqqqqqqgqqq\n" +
            "1-8 p: xpppzdpp\n" +
            "13-15 f: lnlnlkcwgnfqgmfhlwm\n" +
            "12-17 g: gfgtgrvcxggggtggjg\n" +
            "6-8 r: rrrrtwrqrrr\n" +
            "9-12 r: ctldssjlrzhvpmqrtxd\n" +
            "1-6 k: qkkkdkkkkkk\n" +
            "17-18 x: bxrxxbxxzpbxnqxcsmn\n" +
            "2-4 c: ccmr\n" +
            "1-7 m: mmmmfrdmmmhl\n" +
            "9-12 d: ddddddddxddhd\n" +
            "13-14 f: ffffffffjffbbff\n" +
            "4-6 c: ccchcc\n" +
            "6-7 r: rrsrrrrcrrjbrrrr\n" +
            "9-15 w: wzfbtqrwwgtmbxn\n" +
            "6-7 q: qqqqqqrq\n" +
            "1-7 l: lgpqzhlkb\n" +
            "6-8 d: dhddkndp\n" +
            "2-5 m: bjxmmmmm\n" +
            "5-16 t: nbgjntfhpwtbrcftxt\n" +
            "5-7 k: kkkkkhbkkkkk\n" +
            "8-19 t: dsdstttfjhnttttvgttt\n" +
            "3-4 t: ttltttt\n" +
            "1-5 l: flfllllllllbhldll\n" +
            "7-10 x: xxxxxxcxxxx\n" +
            "2-7 t: ttttttctttt\n" +
            "3-12 x: vlxfwpdncxzkmkxt\n" +
            "1-5 b: mbbbbbdbbbtbwbhpbt\n" +
            "3-16 q: fpqkkkqfkqdbrxlq\n" +
            "5-6 p: lpcbtppjpt\n" +
            "6-7 w: wcwwhwv\n" +
            "9-13 v: vvvvvvvvvvvvvvv\n" +
            "1-4 g: vgggtggghgggggggg\n" +
            "2-9 p: mppsrrzwxdt\n" +
            "4-5 f: ffffdfffffdf\n" +
            "2-5 x: xkjss\n" +
            "13-14 z: zzzzzzzzzzzzbhzz\n" +
            "2-10 p: xmtkzpbrrj\n" +
            "17-18 t: ttttttttttttttttttt\n" +
            "2-8 j: cjjqbzpd\n" +
            "4-12 z: zzzkzzhzzpzzdzz\n" +
            "1-2 d: rdcdt\n" +
            "2-3 j: wnltj\n" +
            "7-9 r: rlrfbrdrqrbdr\n" +
            "3-4 s: bcsss\n" +
            "12-14 h: hhhhhhhhhhhbhhh\n" +
            "3-5 h: rfhlc\n" +
            "8-15 f: ffffffflffffffff\n" +
            "3-15 s: ssxsssssssssssss\n" +
            "2-4 h: hlbhshhmhhhg\n" +
            "12-13 r: rrrrrrrrmrvrnrr\n" +
            "3-5 p: ppppjp\n" +
            "1-2 z: zqhdkgqqzfsxkjjzg\n" +
            "6-8 k: kkkkkkzd\n" +
            "1-12 h: qhhhhhhhhxhhhhh\n" +
            "9-14 p: ppppppppqppppfp\n" +
            "2-4 t: tsttt\n" +
            "18-19 t: cttttllttttwxtttttt\n" +
            "10-11 t: rkdbpntntttfw\n" +
            "4-14 m: mdmmgtlmmwmbmmmk\n" +
            "4-6 n: xxhnpmnfnn\n" +
            "15-16 g: ggggggsggggggggng\n" +
            "14-15 k: kpjxmkrksskpbwk\n" +
            "15-18 f: fffffsffffffffnfffff\n" +
            "18-19 p: gwpplnpndvpxgzjvhbpp\n" +
            "8-12 l: ldclrkllbgpwllllcxms\n" +
            "14-19 w: pxsjbtwwhdkptwcxwvr\n" +
            "2-17 m: mtmmmmmmmmmmmmmmmm\n" +
            "12-15 b: nbcsplrmvbjbqlc\n" +
            "1-4 z: bzzszzzzz\n" +
            "1-13 t: tttttttttttttttttt\n" +
            "6-7 j: jjjjjmvjjjjjjjjjjj\n" +
            "10-13 l: llclllllljllllll\n" +
            "11-12 c: mzckxzsbbxcq\n" +
            "2-14 k: kkckkkkbkkkkkrkkkkkk\n" +
            "3-5 s: msssvqszssprssss\n" +
            "7-10 f: fffffffffrf\n" +
            "2-4 l: dlwrl\n" +
            "3-7 v: slqgljmrqrwv\n" +
            "4-6 d: pdddddnddddddd\n" +
            "6-9 f: cnfffpfzfffffff\n" +
            "4-17 v: vvvnvvvvvvvvvvvvvv\n" +
            "7-9 q: qqqqqqqqkqqqqqnqq\n" +
            "15-16 q: qqqqqqqqqqqqqqqqqq\n" +
            "10-11 g: cgtrgggggggggg\n" +
            "10-12 x: xxsxxsjxfxxlx\n" +
            "3-12 j: jjljjjjjjjjjjjj\n" +
            "8-9 c: ccbccczccthcc\n" +
            "4-17 h: hhhfhhshhhhhhhhhhhh\n" +
            "1-2 p: prppr\n" +
            "4-12 q: qqqdqqqqqqqqqqq\n" +
            "7-11 b: bbmbqbrtlwb\n" +
            "4-7 l: lllhlllllz\n" +
            "3-4 r: rrqc\n" +
            "5-14 r: rrrrcrrrrrrqrrrrrrr\n" +
            "10-11 d: pxdcxxjsddd\n" +
            "9-11 s: sssssssspssssssss\n" +
            "1-2 j: jfjljjjjjjjjjjjjjj\n" +
            "3-4 v: vqnvvv\n" +
            "2-3 c: wlcntvmsshxcgzc\n" +
            "9-14 t: rbbljpttwwjtbj\n" +
            "10-11 s: gnrdtfzttks\n" +
            "1-4 x: xpxjxhdxx\n" +
            "9-12 c: chccccccmpfccc\n" +
            "14-16 j: jjjjjjjjjjjjjxjjj\n" +
            "5-6 d: rpdndsbddwdd\n" +
            "9-13 x: thpdhlcwxcxxvxbv\n" +
            "4-6 g: nfsgqnvbntgwvlzlmmxg\n" +
            "3-4 d: dttdcdtq\n" +
            "2-4 n: wnntzbr\n" +
            "2-10 j: jtpszbpjfjcgdjg\n" +
            "6-7 b: bdspbvb\n" +
            "10-14 z: vzznzzzwzlzzqzj\n" +
            "7-8 c: cccccccc\n" +
            "7-11 h: hklhdhssfbz\n" +
            "7-8 h: hhhhhhqzhhhhhs\n" +
            "3-5 b: bcgbwbbbbbdb\n" +
            "5-6 q: qqlxqbgtqpkqt\n" +
            "8-9 q: qqqqqhqkq\n" +
            "2-4 q: qshp\n" +
            "8-13 g: gggggggrgggbgghg\n" +
            "1-5 k: ktcpgpk\n" +
            "2-13 v: mvvwnvfkjrhvvdvvtsvk\n" +
            "12-13 k: kxpkkkckjtkkj\n" +
            "12-18 h: xhqngjkxqqzqhnhhhh\n" +
            "11-12 k: kkkkkkkkkkkjk\n" +
            "2-4 r: rdgrrr\n" +
            "3-4 x: xwjx\n" +
            "2-6 c: lcqzflc\n" +
            "13-14 t: smlkctgbsqpftx\n" +
            "4-5 b: fxtdbzbqbd\n" +
            "4-7 s: wmsssznjzsdkgvdsxhd\n" +
            "2-6 z: wpptkhk\n" +
            "14-16 p: pppppzpppppbprppppp\n" +
            "6-7 c: cccccbw\n" +
            "1-6 h: mhhhhhh\n" +
            "2-3 k: cwkgk\n" +
            "3-4 l: llcl\n" +
            "3-4 m: kmmx\n" +
            "14-20 h: hhhhhhhhhhhrhhhhhhhh\n" +
            "8-12 b: bcmbpbffwghcvjb\n" +
            "10-15 f: fffdfqwmzfdfrfdbpf\n" +
            "1-2 l: hlllljl\n" +
            "1-3 g: vgbgg\n" +
            "2-4 n: zgfn\n" +
            "18-20 w: gmbwtzgzpmdwstsffqzw\n" +
            "9-19 j: jjjjjjjjkjjjjjjjjjjj\n" +
            "16-19 f: fffffffffffffrffffzf\n" +
            "8-20 l: htdlzwsllllccwlflstf\n" +
            "3-4 w: wwww\n" +
            "2-4 b: sbbz\n" +
            "4-6 n: nnrzbbnlcrnsbk\n" +
            "7-8 c: wmzjtbvw\n" +
            "5-7 l: cldlljlzzz\n" +
            "5-6 h: hhzhbhhg\n" +
            "4-5 f: scmrfftkc\n" +
            "11-12 m: flfrbmdpdkpm\n" +
            "6-7 v: xvvvcvkbnvvq\n" +
            "4-11 h: qkjphjpfllhpqnbm\n" +
            "2-5 b: bqbwbbwsb\n" +
            "1-8 c: cqcscccbccrccq\n" +
            "1-13 c: cccccccccccckccc\n" +
            "7-8 h: hhhhhhhs\n" +
            "1-3 l: llxl\n" +
            "6-8 h: hhhhsnkv\n" +
            "6-13 m: mmmmmmmmmmhmpmmm\n" +
            "6-9 n: nrnmmnbnmn\n" +
            "7-14 k: whkpphhkxlnnmkbhtnt\n" +
            "4-10 n: nnnnnnnnnhkn\n" +
            "3-4 c: mcnw\n" +
            "8-13 b: bbbbbbbgbbbbbbbbb\n" +
            "8-9 c: lcccdkjcjrqwck\n" +
            "3-13 w: szmnhsmzwpdbkhtbf\n" +
            "4-5 r: prrrz\n" +
            "9-14 m: mmmmmmmmgmmmmmm\n" +
            "7-8 q: kqpgrqqp\n" +
            "16-17 p: fzxxpcpdhmvmrnvjp\n" +
            "7-9 v: vvvvvvqzxs\n" +
            "3-4 w: qwxw\n" +
            "1-2 x: xqkx\n" +
            "9-10 v: vccmlrlhvdtttfvcxwm\n" +
            "11-14 h: mhvthqhvhhgmfhhhkhch\n" +
            "3-4 n: nqzw\n" +
            "2-5 j: jbjjjjjjjjjjjjjj\n" +
            "11-15 g: bcxggqfmgzgfrdg\n" +
            "3-5 v: gvwvvvrzf\n" +
            "6-7 t: ttzdttr\n" +
            "4-9 j: cgqjqdjvjbfjwdlvdgj\n" +
            "5-6 s: hfflrzksshjqsbvsps\n" +
            "1-4 p: pppn\n" +
            "4-5 g: dprggmpfggbkpg\n" +
            "2-3 k: kbhkkkk\n" +
            "13-15 r: srrrtstrwwxzrrzr\n" +
            "2-4 b: lbbnbzbb\n" +
            "1-4 g: fvgz\n" +
            "5-11 q: hxdhqrqqprpq\n" +
            "2-4 z: zzgm\n" +
            "1-13 w: wwwwhwwwwwwwwwwwww\n" +
            "2-3 k: kkkkk\n" +
            "4-8 g: nlgmhplgcv\n" +
            "1-2 j: zncllmvgjnj\n" +
            "11-13 f: fffffffffffflff\n" +
            "2-8 p: bphqpxkr\n" +
            "2-9 b: bbbbbbfbdbhjpbbbjbbb\n" +
            "9-10 s: zpxnstzwsw\n" +
            "7-16 c: ccccccccccccncsvccc\n" +
            "6-8 r: rrwbrqgr\n" +
            "6-12 v: vvvvvvvqvpvvvvzdd\n" +
            "8-9 z: zzzzbzzmzzz\n" +
            "15-16 t: tfttttntxttqtttc\n" +
            "9-16 b: btbrbfplbbbmbbbbkbb\n" +
            "7-8 q: qrqxrlqg\n" +
            "8-12 q: qqqqqqqpqqqw\n" +
            "5-8 v: jrrlpvvcvkjzjvvvv\n" +
            "11-14 d: dddddddddddddq\n" +
            "5-6 f: rfxmfzf\n" +
            "3-4 t: tttqt\n" +
            "10-14 c: bcccccccccrccfc\n" +
            "3-7 n: snnqplvl\n" +
            "5-6 z: kshzfzhlcsbqwqb\n" +
            "6-11 s: sssssssssmsjsgssss\n" +
            "3-7 v: qgcxvxvg\n" +
            "12-17 v: vkvbsvxkvvnjvvrvvvx\n" +
            "2-4 d: ddrrxbd\n" +
            "8-10 x: tvxxtmgbsxpxbl\n" +
            "7-9 r: rzrbgbrrrrrrmhm\n" +
            "2-4 t: ttttt\n" +
            "5-9 x: xxtwxxnssxlxx\n" +
            "3-4 p: ppdp\n" +
            "3-7 g: ggtgggtg\n" +
            "1-2 k: kbbhjdkfvjqffcss\n" +
            "1-2 l: lrlvlll\n" +
            "10-12 x: xjkbqxkxzxxq\n" +
            "7-9 d: dddhdkpdfdf\n" +
            "5-8 m: mmmmmmmwm\n" +
            "3-9 l: sfrjlzhcll\n" +
            "7-18 m: mmmmmmcmmmmmmmmmmmm\n" +
            "1-3 w: mwplxwwww\n" +
            "7-8 t: tgtctbtrtdtttt\n" +
            "3-6 p: lfpbbgfbpdhnqz\n" +
            "5-6 d: ddddrd\n" +
            "1-3 b: llbbbbb\n" +
            "4-7 r: ktbrncrrnnsrr\n" +
            "8-10 r: rrrrrrrfrrbrr\n" +
            "1-8 l: wlklvlllnljlgtzll\n" +
            "2-4 m: mmhmmxsm\n" +
            "10-12 c: cmwkcnczsxmcrmjtc\n" +
            "2-8 q: qmqqqqqzqq\n" +
            "7-9 v: xvvvvwdnzzv\n" +
            "3-7 j: lsjvmbrjjmpcwqnvvdgc\n" +
            "3-9 l: bgmllldjrzhllsclc\n" +
            "1-6 p: ptppfjpqpp\n" +
            "7-8 r: mctrrstrrxrqtmrr\n" +
            "7-8 d: qddddddxddddddddd\n" +
            "4-11 r: rrrrrrrrrrbr\n" +
            "4-8 s: lsfvtfss\n" +
            "4-9 c: zcccccccj\n" +
            "11-12 v: vvvvvvvvvvvm\n" +
            "4-8 g: rggzlfgtm\n" +
            "3-8 j: jjjjjjfhjsgj\n" +
            "3-4 m: fmhmm\n" +
            "15-16 l: ltllhlljtllllbtlllgl\n" +
            "12-13 c: cccccvcccccqccccc\n" +
            "6-7 q: qqnlqqhqqq\n" +
            "1-8 z: znjqzxpz\n" +
            "10-13 k: kxzmkbxnkbkktmkk\n" +
            "8-15 k: bskzvggzsnlnxzz\n" +
            "9-10 v: vbvvgvcwvs\n" +
            "5-8 h: qhsnhhlhwpvzfb\n" +
            "15-16 g: gdcgggggggtgcgtg\n" +
            "8-9 z: fbgdnrzfb\n" +
            "6-7 d: ddkdddh\n" +
            "4-6 w: xzgfwwlbxft\n" +
            "1-3 h: hkjhh\n" +
            "1-3 p: pwprlp\n" +
            "8-12 j: jdjjjjjdjjcjvjjjjjj\n" +
            "11-14 m: bdsfwddfkgxsmrmm\n" +
            "3-10 m: tmmcmfmmjmm\n" +
            "3-4 b: dwhbzfjxl\n" +
            "2-5 n: nnnnjcnnn\n" +
            "16-17 v: vvvfnvvvltsxhrvvm\n" +
            "1-7 v: qvvvvvwvvvdvv\n" +
            "2-14 k: nxqblwwqmhqzkm\n" +
            "3-4 t: ttts\n" +
            "5-6 c: clnnfk\n" +
            "12-13 s: sssssssssssts\n" +
            "7-14 d: ddqdnwdkdmhddg\n" +
            "3-4 t: tmsttm\n" +
            "9-11 x: xxxtxxxxxxqxwntxj\n" +
            "8-14 l: lllqklwlvlllmbslzlln\n" +
            "9-12 n: sdsnnfncxnwnrn\n" +
            "1-5 f: qfffff\n" +
            "6-9 r: rzmphlrgrr\n" +
            "1-4 m: grdm\n" +
            "4-5 s: ssxsg\n" +
            "1-4 n: xhnznnxnnn\n" +
            "2-6 r: mcwldgbqlqsckgzlrd\n" +
            "1-3 l: llmllll\n" +
            "3-4 p: pjtgdnfjfcjtcnpgxpzq\n" +
            "6-7 m: mmvmmmtn\n" +
            "17-19 h: qgmhhhwwwhqhmhhthhch\n" +
            "3-14 s: lhmnsfdrvnngrsfhxd\n" +
            "1-6 p: pppppwp\n" +
            "4-6 l: lzllltrl\n" +
            "3-4 c: rpxccsc\n" +
            "13-16 h: qsdznfqmsftqqthh\n" +
            "2-4 k: wsvkm\n" +
            "1-18 h: chhhhhhhlhhhhhhhhhhh\n" +
            "17-18 d: xddddddddddddddddddd\n" +
            "2-3 t: jtbrhpzjfpzhcmjql\n" +
            "10-11 n: gjngnnncncnn\n" +
            "7-13 r: rrrrrsrrrrrrlwrrr\n" +
            "10-12 l: llldllslbldllwl\n" +
            "17-19 m: mmmmmmmmmmmmmmmmfmm\n" +
            "10-14 n: nnnnnnnnnbnnnnn\n" +
            "17-18 x: xrxcxxxxxxxxxxxxxxwx\n" +
            "3-4 b: lvxb\n" +
            "5-6 r: rrrrrrr\n" +
            "13-18 l: lllllllllllllllllpl\n" +
            "8-12 m: mmmmmmmqmmmmmmmm\n" +
            "7-8 l: llhqlllh\n" +
            "3-8 p: nmrppdvpxcphxgmkpbsl\n" +
            "9-10 v: hvsbttgsdvvj\n" +
            "5-9 k: kgmvzzzckkgldk\n" +
            "15-20 x: xqxxxjxxxxxxxxxxxxxl\n" +
            "5-6 t: bbwpwtwbhwgqttzjv\n" +
            "6-13 n: klzcfnnjqxrhjwpjfxnk\n" +
            "5-8 d: pcnndzddddnsdqh\n" +
            "5-14 k: kblbtvkwltfklk\n" +
            "4-11 q: zxwdkqqkvqq\n" +
            "10-12 s: tsssssssssssss\n" +
            "3-5 r: rddsrrdksfqfrgr\n" +
            "7-16 h: vdvhlsjxgvrbrxnhns\n" +
            "3-4 z: zxtz\n" +
            "4-8 x: xmnxdwmh\n" +
            "11-12 r: gwsnfrnckrrxrx\n" +
            "3-9 q: qqqqqqqqwqb\n" +
            "9-14 f: bfnfffffvfpfffff\n" +
            "6-9 p: pvpppkppcpp\n" +
            "3-4 m: mmmz\n" +
            "3-5 j: jjjjmjsjjrlkjjjjj\n" +
            "4-6 p: jpbpjs\n" +
            "6-9 r: bswdsrksdrzrgrfmjr\n" +
            "8-10 l: lllllllxll\n" +
            "3-7 v: vvhvvvvv\n" +
            "4-11 n: mnjpbldngrrkbthhmdp\n" +
            "2-4 r: frlrfblsrfzrhtpk\n" +
            "16-17 h: nbghhnzshclxhhmkr\n" +
            "2-5 z: zfzvzzzzzzzq\n" +
            "1-5 l: lllzlfl\n" +
            "9-10 d: dddddddddzd\n" +
            "11-12 p: pspppppppbzp\n" +
            "5-9 t: thzttpxrdhttdwqjsg\n" +
            "7-10 w: tfdfwlwwzdvpnww\n" +
            "4-6 z: fvcljzllwhbzscx\n" +
            "14-15 m: mmmmmmmmmmmmmcd\n" +
            "8-11 d: hgdmwgsdkdbghb\n" +
            "13-15 v: vmvdvvqvvvkvqvvv\n" +
            "13-14 f: fffffffclffffffmf\n" +
            "2-5 s: ssscn\n" +
            "11-13 w: wwwwwwwwwwwwww\n" +
            "7-9 l: xnwrlkskll\n" +
            "8-14 g: vggglvcrgscpgggt\n" +
            "4-5 w: wwwww\n" +
            "5-11 w: wwwwswwwwwwwwwww\n" +
            "6-7 g: gggbvjg\n" +
            "14-18 q: wqfqqqqqqnqsqrqqqq\n" +
            "6-7 z: zzzztzqczzzzz\n" +
            "6-12 n: wnnnnnnxftnkznpvvl\n" +
            "10-16 j: jjjjjdjjjrhjjjjj\n" +
            "1-10 l: lllllllllrll\n" +
            "9-13 g: gdgggggggggkggn\n" +
            "6-8 r: rrrrrrrs\n" +
            "16-17 k: kkkkkxkkkkkkkkkck\n" +
            "11-14 b: bbbjbxbfmqscqbdmgg\n" +
            "3-8 d: sjdkmjppbdddhdxd\n" +
            "6-7 g: xhkhwgqpbg\n" +
            "11-12 x: xxxxnxxwgxxbdl\n" +
            "6-8 c: cccscccwcccccccccc\n" +
            "9-16 h: vhhhhhchwnghmkzhr\n" +
            "5-9 v: vvvdnvvvvv\n" +
            "4-16 n: nmqncgnbfhqnnpnbxwrl\n" +
            "3-5 f: fljrf\n" +
            "13-14 m: mmmmmmmmmmmmgfmmmmmm\n" +
            "5-6 g: ggnggd\n" +
            "2-6 w: wlvhvw\n" +
            "13-18 h: hhhhhhhhhhhhhhhhhvh\n" +
            "7-19 m: mmmmmmmmmmmmmmmmmmwm\n" +
            "4-12 k: mcvtrtsdkvkkfjrmkn\n" +
            "1-8 t: qvmrtttn\n" +
            "6-7 f: fffffsf\n" +
            "10-11 m: mmmmmmmmmjl\n" +
            "15-17 v: mvrhvvvvnvrvzrvvfv\n" +
            "10-14 m: mmtmmmnmmmmmmxm\n" +
            "4-16 b: vcscdqcbcxswjfdbrqbx\n" +
            "8-9 z: zzzzzzznzvz\n" +
            "4-6 g: ggnggdpgggg\n" +
            "2-4 d: hddxxnzzw\n" +
            "9-10 g: gggggggggj\n" +
            "4-7 k: kkkvkkkkkk\n" +
            "1-3 r: rrrrj\n" +
            "14-15 w: wwwwwwwwwwwwwwwww\n" +
            "2-4 n: brfmln\n" +
            "18-19 b: bxbbbbbghbbbbbbbbwb\n" +
            "10-12 q: dqqqrqwcqgqqf\n" +
            "2-5 g: sxfzgtrxkrmstdzfmw\n" +
            "3-4 d: pcddq\n" +
            "11-16 w: sbqwlwzwwwwwtwww\n" +
            "2-12 c: wrccqxtccccchcccjcj\n" +
            "16-17 b: bbbtbbbbbbbbbbbqb\n" +
            "3-13 t: tttttttmgktdthtp\n" +
            "1-3 t: ttcg\n" +
            "13-14 z: zczzzzzzdwkzqz\n" +
            "5-6 n: bnjhnjhnnq\n" +
            "2-9 b: bjbgbzmlbbklbwt\n" +
            "4-5 b: dtlbbwtjbkzzbghbghzk\n" +
            "10-16 p: ppppppqpppwnpppppppp\n" +
            "5-6 b: cbbwtbjkm\n" +
            "15-16 p: ppppppppppppppqd\n" +
            "4-8 m: lgmmhgktslzhbvw\n" +
            "2-4 h: hhdlhhhhhhhhhhh\n" +
            "14-18 k: ktmkkkkkwkklkjrkklfk\n" +
            "5-7 x: sfxxsxx\n" +
            "8-9 v: lkvxdpvjv\n" +
            "7-8 r: rrrrrrsr\n" +
            "4-6 b: btcbbv\n" +
            "7-13 n: zhnhjhnmkzdbt\n" +
            "7-9 j: jvjjjjjjjjjjjjxjj\n" +
            "1-4 v: hdvfv\n" +
            "2-5 f: rznpnxqwncmtkwfxcxqh\n" +
            "16-17 x: zxgbhltrdhxkvvxsxf\n" +
            "1-2 h: hkhhh\n" +
            "3-4 h: zhxc\n" +
            "4-9 z: vsmzhzwgjxfg\n" +
            "11-13 x: xxxxxxxtzxxxc\n" +
            "11-12 d: dddddddgddqj\n" +
            "4-11 f: zkdhqnpgbff\n" +
            "2-3 q: qqlqgqqqv\n" +
            "4-9 b: bvnblwhbbkswmrhtf\n" +
            "7-13 t: cztskdtqdtrkt\n" +
            "4-5 f: fffcsf\n" +
            "4-9 f: ctblqrflf\n" +
            "1-2 l: lmllqhlnll\n" +
            "3-6 v: vvqvvvvr\n" +
            "7-9 b: bbrhbkjbb\n" +
            "1-8 p: xpppppppp\n" +
            "7-10 k: ckkpmktkqksgkkk\n" +
            "1-7 m: lmmmmmmmmmmmmmm\n" +
            "11-15 v: vvfvvmvvvvdvkvv\n" +
            "10-11 b: kbbbbbbzbhbb\n" +
            "11-12 l: jltgggtlcggllt\n" +
            "10-13 q: kqnqqqqqqqqqq\n" +
            "6-7 c: cjcccczc\n" +
            "5-11 t: kdtstshrhfkcx\n" +
            "3-12 v: vlvfzvwvxvvhvvsvvcvm\n" +
            "9-10 t: xttttttttttt\n" +
            "8-10 z: hctlkgjzvzh\n" +
            "3-5 g: gtkwgk\n" +
            "16-17 w: wwswwwwwwwwwwwwwwqww\n" +
            "4-11 j: lbmwjzjxjpjhzjjpbj\n" +
            "4-5 c: klbxc\n" +
            "3-5 w: wlhvb\n" +
            "4-8 x: xgxxxxxxxxxxxxdxnxx\n" +
            "2-5 n: nnnkhn\n" +
            "1-2 d: dxfd\n" +
            "11-12 w: wjcqszwqwkcb\n" +
            "6-11 v: sqpgzhnvndtmvvwl\n" +
            "3-4 m: mmmqmmm\n" +
            "1-3 d: mddb\n" +
            "6-7 w: wwwwwnwwwwwwww\n" +
            "12-14 z: zzzzzxzczzzrzzz\n" +
            "5-10 f: mtcmmhfftft\n" +
            "10-14 x: hhgvmxbwgxdcnz\n" +
            "10-16 z: wzfzzmlmxxfhzqcbsnl\n" +
            "3-4 p: ppvkppp\n" +
            "8-11 h: hhhkhhhjhpbhhhh\n" +
            "6-12 f: ffffdwffrsfffrffnfpk\n" +
            "5-11 z: xqwzzzzbzpwk\n" +
            "7-9 c: crccccccscccccc\n" +
            "4-5 b: qpcnz\n" +
            "2-13 m: lmnrrzfhmbwtmqbsg\n" +
            "12-13 k: kkkkkkdkkkkkmk\n" +
            "10-14 q: sdqfbqszdjhqfq\n" +
            "8-13 h: hhhhhjhhhhhhbhh\n" +
            "2-4 g: gfdb\n" +
            "12-19 n: wtrhndnnnbwnnnnjnnn\n" +
            "5-6 n: zdwnpn\n" +
            "3-5 f: ffsffffff\n" +
            "11-16 r: rrrvrrrrrrwrrrrrlrrr\n" +
            "6-8 n: nnnnnfnnn\n" +
            "10-13 b: brnlbblbkbbbjbbhx\n" +
            "7-8 q: ftrfnqgqc\n" +
            "11-12 c: ncccccccccgcccn\n" +
            "3-4 z: tzzctzwzzvz\n" +
            "3-5 t: tzrqg\n" +
            "7-10 m: mmmmmmrmmqmmm\n" +
            "1-2 c: cdccfcccc\n" +
            "10-11 k: kkkkkkkkkwkk\n" +
            "6-18 x: qndxdgmjvpppddwkbt\n" +
            "8-17 c: pxhszsccndlbzkwgvx\n" +
            "3-4 p: qlrvwdxpqtgwjrtqcc\n" +
            "2-4 q: lkjq\n" +
            "17-19 f: pffgflzxrxfdxffffnz\n" +
            "3-11 x: kzsvmhcxnwj\n" +
            "6-7 x: lxxxxxxcm\n" +
            "1-8 n: nnnnnnnrn\n" +
            "2-5 r: rtrrnr\n" +
            "2-4 n: csvhrvhlp\n" +
            "7-8 b: lbbpdbkb\n" +
            "2-8 t: ztcrbvmst\n" +
            "3-4 r: rwrr\n" +
            "7-15 b: tbtrrbbpwsrvklqb\n" +
            "9-13 d: dcfsgddmdsjgg\n" +
            "2-7 d: mvdzscd\n" +
            "6-8 d: jrjjdndq\n" +
            "1-3 m: mhmvhtmmlbztvmsvmtmb\n" +
            "10-12 c: ctwjbpkchccmbqw\n" +
            "2-3 z: jvzwcrbgqbhvzbf\n" +
            "2-7 g: qbwsdbg\n" +
            "4-7 s: jsxpbmsmkhktfdq\n" +
            "11-13 r: rrrrrrrrrrhrqr\n" +
            "9-14 d: zddcdgddddxddntddm\n" +
            "1-15 x: jgrxxxxfxkgbmsxzx\n" +
            "2-17 p: kcppppkppppppppwm\n" +
            "12-19 k: kkkkkkkkkkkmkkkkkkkk\n" +
            "1-4 x: nzpxg\n" +
            "5-12 p: xcbppqnppqgtrm\n" +
            "11-14 h: dlhzhhhsbllcwhh\n" +
            "13-14 q: qqqqqqqqqqqqqcq\n" +
            "11-16 t: ttgnswrltltttjtj\n" +
            "14-15 t: ttttvtttftttttjtc\n" +
            "3-5 s: xssns\n" +
            "9-11 q: mlqqtqnjqfl\n" +
            "3-4 z: nzzhz\n" +
            "2-5 k: skwbwkwgzj\n" +
            "1-3 p: pppppcppppbpp\n" +
            "5-10 r: rrrrlrrrrrr\n" +
            "2-3 l: jlffrztcckl\n" +
            "3-5 t: ttftttttr\n" +
            "3-6 q: qtqtmnlqck\n" +
            "1-4 v: vxfvmvxwvvjbxp\n" +
            "1-5 z: tzzzzszvzzrmzmz\n" +
            "10-11 l: lllllblllcx\n" +
            "1-4 p: vppppp\n" +
            "6-12 v: zvrwvvvrvhzb\n" +
            "2-4 x: xxnv\n" +
            "1-7 w: hwwwwwgwgwwbwqw\n" +
            "3-7 w: wwwwwlfw\n" +
            "5-6 l: kkpltd\n" +
            "4-5 d: ddnrdk\n" +
            "3-6 c: cncvkt\n" +
            "8-9 j: vblczlfjjkj\n" +
            "7-15 d: ddddxdgdddddddjddd\n" +
            "4-7 z: vvmzdspzwptz\n" +
            "5-7 t: cdrtfqt\n" +
            "6-9 j: jjjjjdjjjjjjjj\n" +
            "2-5 j: ljptkvvfl\n" +
            "6-7 l: vhhnllgx\n" +
            "5-6 g: gpcxwvgpvvgg\n" +
            "5-12 q: plzqqnqzrhqgljj\n" +
            "8-13 k: zkckdknkxkgkvmmkd\n" +
            "4-10 s: jkvstssfcsrckjnzzbsl\n" +
            "9-11 n: nlknnnnggnvnnnnn\n" +
            "8-9 s: ssssrsgstk\n" +
            "16-18 r: rrrrrrrrrrtrrrrbrrrr\n" +
            "4-5 f: qxrzfcgfqfp\n" +
            "2-10 p: pphtppppppplwpsp\n" +
            "2-5 q: qqqqsq\n" +
            "6-15 j: xjkxkjxxkjznjjj\n" +
            "9-13 f: fvfvjlfmltfgf\n" +
            "3-6 j: jnsrcj\n" +
            "1-7 h: vhhhhhhh\n" +
            "4-5 q: qrqqqf\n" +
            "2-3 v: mvxb\n" +
            "4-11 l: lllllllllldl\n" +
            "7-17 k: mkcxhcmbcpjckkqznh\n" +
            "7-9 v: vvpgvvvvs\n" +
            "7-11 j: jjjjjjjjjjjs\n" +
            "2-12 v: mlxjljvffxgv\n" +
            "3-4 t: hhfn\n" +
            "14-16 w: kwfwwqwcfcwwfmww\n" +
            "5-6 j: jjjjjg\n" +
            "11-12 n: nnnnnnrdnnmnn\n" +
            "8-9 b: dsbbbfbbbb\n" +
            "3-4 j: jjcjjj\n" +
            "1-3 r: wrnr\n" +
            "10-11 p: pppppppppqppp\n" +
            "12-13 v: vvvvvvvvvwvvvv\n" +
            "7-9 v: vvvqvvxvdvxv\n" +
            "9-14 r: mmrrrrnrrxrrrwrrrrrr\n" +
            "5-6 k: kkkkbkkr\n" +
            "13-17 v: dbvgrchdpnzvxrdfv\n" +
            "4-9 c: ccjbccqcpcclcc\n" +
            "6-8 m: mbjmmxnb\n" +
            "2-6 h: hhdhnvcc\n" +
            "9-16 t: tttttttttttttttgt\n" +
            "12-16 n: nnnnnnnnnnnnnnnwn\n" +
            "3-14 z: zzdzzzzzzzzzzzz\n" +
            "3-8 k: pmktwckzn\n" +
            "9-13 q: gqqqqqqqrqqqqq\n" +
            "3-6 l: lllllddll\n" +
            "7-8 x: slxxzplxsxkcxlxxx\n" +
            "2-5 v: vwvvd\n" +
            "6-7 n: xxnnnmnnn\n" +
            "2-4 z: zczz\n" +
            "2-12 p: pppppppppppvp\n" +
            "2-4 h: bqwhv\n" +
            "5-7 t: btzttjg\n" +
            "4-9 c: sxcskxxbcv\n" +
            "1-6 c: cccccpc\n" +
            "9-13 l: bcsllbvbjhrflt\n" +
            "5-9 c: zprfctdnt\n" +
            "1-5 z: zzzzz\n" +
            "4-8 h: bpshnhxhrbk\n" +
            "4-7 l: bqclvxf\n" +
            "5-6 m: mmmmmgwcmgjj\n" +
            "13-18 m: mmmnmmmmmmmmpmtmmgm\n" +
            "1-5 w: cwwgwwwwwww\n" +
            "14-16 h: hhhhhhhhhhhhhqhhh\n" +
            "6-7 v: bvvjvvbvvv\n" +
            "5-13 b: pbcbbqmbcsfblc\n" +
            "17-18 j: jjjwjsrjjmkjjqjjjj\n" +
            "4-6 t: ntttpt\n" +
            "6-7 v: mvvnvvc\n" +
            "11-12 v: vclgnzbvtvvjvs\n" +
            "8-13 r: rlrzkjkrrxmdvzgt\n" +
            "5-7 n: nnnnnnsnnnnn\n" +
            "3-6 q: qpkjpq\n" +
            "2-7 v: hvgnjfrkvx\n" +
            "6-10 g: xgmrggggpbggfqgdpm\n" +
            "9-10 s: ssssssswfszsdssszss\n" +
            "5-6 p: pppjppwpp\n" +
            "2-5 d: ddddddd\n" +
            "9-13 p: ppjhpbppxpxxt\n" +
            "10-15 t: cgtcnlltzdkbcjtvxs\n" +
            "8-11 m: dkmmvtdmkbhmk\n" +
            "3-4 z: rzzqzw\n" +
            "4-8 z: zcxzswbzzqzxwkzz\n" +
            "3-4 s: jsts\n" +
            "2-7 b: bsbbbbbbbbbbb\n" +
            "11-15 l: jjkslsltvfbqshl\n" +
            "3-14 c: cqtxcgmcgvgfcccmg\n" +
            "1-8 f: fbfwffhfbxffhlx\n" +
            "4-11 r: drrmrrrzcfrj\n" +
            "5-6 p: pwpvjp\n" +
            "11-14 d: pnrddqwdlpdbddwg\n" +
            "9-10 r: rrrwrrrznrrgqsr\n" +
            "3-12 v: vsvvbvvkvvpdrvvv\n" +
            "2-5 t: mtfqjrjlthk\n" +
            "13-17 r: rrrrrrrrrrrrrrrrtr\n" +
            "7-8 n: nnnnnnhnn\n" +
            "3-4 r: wrpr\n" +
            "1-14 p: ppppppppppppppppp\n" +
            "8-9 m: vzkbzwnmwfqmmmmcmmnd\n" +
            "11-14 p: pppnpvpwppvpppppppp\n" +
            "17-19 h: lzhxlhhchxhbxhwvhsx\n" +
            "10-11 n: nnnnznnnnlp\n" +
            "3-12 f: kwflsfqflxpzbgxzdhzv\n" +
            "8-10 x: xxvxxxxvxsxxlxxxx\n" +
            "1-2 c: dclflczlj\n" +
            "4-9 w: wwwtwwwwwww\n" +
            "2-8 t: pfvtlbtxt\n" +
            "4-9 f: pnfkffkfnh\n" +
            "8-10 v: vjvvvvvvvvvvvv\n" +
            "3-13 s: mfshscgmmrvzw\n" +
            "6-10 g: gzggggpggkggzggggg\n" +
            "13-14 n: fnnnnnnnnnwnrnnn\n" +
            "4-14 k: lbvkwrkjkxjskg\n" +
            "9-11 q: qqqqqqqqsqgq\n" +
            "17-18 q: qqqqqqqqqqqqqqqqqd\n" +
            "6-9 s: spsssgsrrssss\n" +
            "8-14 m: qmmqjmmmmtpmnzgmm\n" +
            "1-7 m: bmsrmmmmmmm\n" +
            "14-17 k: kskdbkkkkdkkkktkqkkk\n" +
            "4-5 c: ccccgfc\n" +
            "2-5 k: kkkkzk\n" +
            "2-11 q: qqwqlnqqqhtdvxqrc\n" +
            "4-6 m: fdxkmmd\n" +
            "7-10 j: mjgftcmjmjj\n" +
            "17-18 m: mmmmmmmmmmmmmmmmnm\n" +
            "2-4 v: svvv\n" +
            "6-8 x: jxxhrxlp\n" +
            "4-10 s: dsvdbsssmscs\n" +
            "18-19 k: zwdgknqvqkgdhdhktkmr\n" +
            "2-7 h: jdflgfh\n" +
            "6-8 z: zmpzzzzzzzzgz\n" +
            "3-6 m: mmrmmm\n" +
            "4-8 w: wwtwktws\n" +
            "4-10 k: dkjkqkkzvk\n" +
            "3-7 b: bbbbbbfbbb\n" +
            "4-12 z: zzzzzzzzzzzzz\n" +
            "5-9 z: nmqdzzkzzzbj\n" +
            "4-11 z: fzzgzzzzzztzz\n" +
            "1-7 w: whwwwzrw\n" +
            "5-6 t: tjtttv\n" +
            "9-11 v: vzvhvxvvnvwvvv\n" +
            "2-4 t: pkjtpp\n" +
            "14-15 n: njpwjnsbnnnnngnnvnnn\n" +
            "5-15 k: qtmvkkdjkslkqvk\n" +
            "2-4 s: skszs\n" +
            "2-3 g: zggjhgxzn\n" +
            "16-17 p: ppppmppppppppppnppp\n" +
            "4-10 z: zzzzzzzzzzz\n" +
            "17-18 s: sssgsssskssssssssbs\n" +
            "5-8 m: mmmmmmmbm\n" +
            "1-5 l: llllmlql\n" +
            "3-13 z: bmdwpgvzfdlgzgl\n" +
            "1-4 p: pjplgjr\n" +
            "1-9 v: vvvzvrvvk\n" +
            "6-18 w: whwpwwflbcwwvwwwwst\n" +
            "19-20 n: nnsnnjnnnnnnnnnnnnkx\n" +
            "9-10 m: rlmxrnqrmkmmwmmmmm\n" +
            "15-17 s: lvssssslssfsssksfb\n" +
            "3-4 q: qqqpq\n" +
            "7-13 h: hhhhhhhhhhhhdhhhhhhh\n" +
            "2-6 h: dvkfhhmk\n" +
            "4-6 s: nczssv\n" +
            "10-12 p: pppppppppppdpprp\n" +
            "16-18 s: sssssssssssssssgsg\n" +
            "7-12 h: hhhhhhvhhhhhh\n" +
            "4-12 f: ffftfffffffwff\n" +
            "4-7 s: csqcpssbgvvmwdb\n" +
            "6-10 p: ppppvppppdppd\n" +
            "6-8 h: hxjhthhgzh\n" +
            "3-10 f: fffffffffsf\n" +
            "4-11 g: trggxlrnqrgh\n" +
            "2-15 w: wjxwtvkwwpgwwww\n" +
            "1-4 v: zjxv\n" +
            "7-10 f: fffffflqff\n" +
            "4-6 g: mgwgpbg\n" +
            "1-10 z: vvzzzzzvzz\n" +
            "6-7 f: ffffffnf\n" +
            "11-15 w: wxzwwqdnnwwxjlwplcl\n" +
            "10-11 s: hsslzjgsssvxsshnsc\n" +
            "4-12 n: tlxdnpznjbknt\n" +
            "7-8 k: mkhcvjxk\n" +
            "10-12 j: jjjjjjjjjjnm\n" +
            "2-7 c: fckckdpcksjckwcc\n" +
            "3-8 s: sssdxssw\n" +
            "12-14 t: ttttttttqttxttttpttt\n" +
            "6-7 g: gggggggg\n" +
            "5-10 f: fqffzffffffffgf\n" +
            "6-7 t: ztqhpbt\n" +
            "5-12 w: swwfwwwwwpwbwj\n" +
            "2-4 w: qmww\n" +
            "5-8 v: vvjnvvpv\n" +
            "7-8 p: bcbtnppbxnnwpr\n" +
            "4-12 z: zzkzdxntzlfbkkzzzw\n" +
            "8-9 s: sssssssss\n" +
            "15-18 h: jhvhhhcxwhhhhmhhhj\n" +
            "6-10 w: bwwwwwwwwwwwww\n" +
            "5-9 l: mtqlhlwlh\n" +
            "5-7 l: ljllnllblpl\n" +
            "15-17 h: hpgdkhsjwfnsjmhqxf\n" +
            "3-4 g: gggxgggg\n" +
            "1-2 q: qdqm\n" +
            "6-10 n: hnnnqknnnnnlnnnnp\n" +
            "13-17 q: djstfsmmqlshqqbqnf\n" +
            "6-7 z: qzlzxzw\n" +
            "7-12 g: qhghvbwdcvkgjl\n" +
            "7-15 z: zzzzzznzzzzzzzzzzzzh\n" +
            "3-6 w: zchpwvw\n" +
            "3-4 c: wmbjp\n" +
            "6-9 k: tckbvkkxkkqk\n" +
            "11-13 p: pcppppppppppppbp\n" +
            "5-7 r: rrrrsrxrr\n" +
            "6-10 c: ccccczcccccccccc\n" +
            "7-8 j: jjpjjplj\n" +
            "5-7 m: mjmmmjrmfmmmmmmmm\n" +
            "1-7 t: ttttttnttvpt\n" +
            "6-12 t: tttfwtttttttttttttt\n" +
            "7-17 x: hxwgrqqlxmrxrcwsx\n" +
            "3-8 g: vjcgqrjhlq\n" +
            "13-18 n: nnnfnnngnnnnjnnnhln\n" +
            "13-15 f: ffffffffffffrbff\n" +
            "13-15 x: xmswzjhtthggslslgx\n" +
            "12-13 g: ggggggggggggggg\n" +
            "3-9 f: cxfskjcbmhmmcpwn\n" +
            "5-7 h: jxzbhbh\n" +
            "2-3 m: mhmlmq\n" +
            "1-3 m: rmmmgmzvcghdtgmsmnm\n" +
            "14-15 s: wzssphxtsskpssr\n" +
            "8-14 p: kppjppgfpprftj\n" +
            "2-7 r: prnmlrrbm\n" +
            "2-5 v: vvvvtvv\n" +
            "1-5 n: nnnnzn\n" +
            "2-5 t: xtlnfwhgvltx\n" +
            "3-4 v: gvtv\n" +
            "2-8 k: kvkstkfz\n" +
            "2-6 j: jdjjjnjjjjzjjjj\n" +
            "3-4 s: sshwsssss\n" +
            "2-10 w: mnhkdtwdzwvsq\n" +
            "6-8 b: bbbbkxbbtbbkbt\n" +
            "14-19 h: hhhhhhhhhhhhhhhhhhhh\n" +
            "6-10 d: ddddddddddddddd\n" +
            "10-13 t: ttttttttthttjttt\n" +
            "4-5 c: ctscw\n" +
            "8-9 b: bbbvbbgmb\n" +
            "10-12 s: sxssshsssswsscsx\n" +
            "3-7 r: rdhrrkrkrrrrcrhrrr\n" +
            "8-10 j: wjsslzjjntjjwjs\n" +
            "1-4 q: gqqw\n" +
            "4-6 t: tjlhvrt\n" +
            "2-10 s: ssssssnssssssssx\n" +
            "7-8 x: xxxxxxfw\n" +
            "6-13 r: sxtcgrffrpdprnklbxbw\n" +
            "1-3 p: ppbppppppp\n" +
            "2-3 b: jbfr\n" +
            "1-7 m: cmmmmqm\n" +
            "4-5 t: tttzt\n" +
            "7-9 s: zwbbbssvl\n" +
            "10-13 w: wwwwwwwwwwwwdw\n" +
            "13-14 n: nnnnnnnnnnnnnmkn\n" +
            "5-11 q: jpbzqwqbwttgzn\n" +
            "4-5 k: kkkwkkk\n" +
            "10-17 w: sgtklkflsrfqxfwhjm\n" +
            "6-12 w: wwjqwwlmphwkwwwwwjw\n" +
            "2-13 p: ppppppppppppzp\n" +
            "2-16 h: tslcwztxxtchgqlxsbx\n" +
            "2-9 p: slptvtljpxdkf\n" +
            "10-12 z: tnzzghzzgzfn\n" +
            "3-18 f: ffxfffffffffffffff\n" +
            "1-2 p: prdpdghkckdgpl\n" +
            "6-8 x: fxxnbwrx\n" +
            "7-9 z: zmzkzdpgjzzz\n" +
            "7-14 p: pppppppppppppppb\n" +
            "7-10 l: xltlzllllljzxlll\n" +
            "18-20 n: nnnnnnnqnnnnnnnnnmnb\n" +
            "15-18 p: pxmqxpmqwfntrpppmf\n" +
            "1-15 v: kgmvwvrvmcvtrvvwv\n" +
            "2-8 g: gxggggggg\n" +
            "4-5 f: clfjfqmpffjfff\n" +
            "3-5 r: rpjkf\n" +
            "2-9 h: hhhhhshhrhh\n" +
            "2-5 z: zxzzz\n" +
            "5-11 k: kkkkkkkkkkkk\n" +
            "8-9 n: nnddcfntnrgnnrnnc\n" +
            "1-11 f: dfffffffffff\n" +
            "2-4 x: dzphvg\n" +
            "4-5 w: mnzlr\n" +
            "2-6 f: jhrkfmg\n" +
            "2-17 z: czzvvzzczznzhwzbzz\n" +
            "2-5 r: xrjrg\n" +
            "2-3 g: gggg\n" +
            "7-9 s: ssssssbsssss\n" +
            "17-19 k: kcwktkxkkbkqnwkkkkdz\n" +
            "1-16 f: zmxdffmfgffxrffffqf\n" +
            "7-8 q: qtmrkbqjq\n" +
            "8-9 q: qqqqqqqqx\n" +
            "10-18 n: nnnnnnnnnznnnnnnnnnn\n" +
            "16-18 x: xwxxxxxxxxxxxxxxxrxx\n" +
            "15-18 t: tttttftptttttttcttt\n" +
            "10-11 h: hfxnlbsqxphtmstbhdn\n" +
            "7-13 z: vdzdzmzxvfzzz\n" +
            "2-5 n: nnpqgnnqnb\n" +
            "12-16 v: pvjvvnbqzjnvvvvpjv\n" +
            "4-5 d: ddddk\n" +
            "4-8 l: lxvhlbclhgd\n" +
            "3-12 v: vvkvvvvvvvvvvvvvvvvv\n" +
            "17-18 j: jjjjjjjjjjjjjjjjdj\n" +
            "6-7 b: ckbdbcsbb\n" +
            "9-11 q: qrhxpcjjqbqt\n" +
            "8-14 h: hhhhhhhhhhhhklhhhhn\n" +
            "2-3 b: bzbjb\n" +
            "2-15 w: nnmdgzhsvhpvswltvt\n" +
            "1-5 l: lbclz\n" +
            "15-17 d: wlddgdxsdcdfdcgdd\n" +
            "18-20 q: dqsldgqqfqwsstqlmqtz\n" +
            "1-6 q: qqqqqdq\n" +
            "2-6 j: jpjjjjjj\n" +
            "13-15 p: ztjlhtnsgphgxccpfsp\n" +
            "6-13 m: ghvvmrglmmmcm\n" +
            "3-6 b: nbbrmrfdlbs\n" +
            "1-3 j: fwhjsr\n" +
            "7-10 p: gcppcppzpppp\n" +
            "4-12 r: rrrrrrrrrrrrrr\n" +
            "16-20 d: djdddvdsddddlmddddpm\n" +
            "14-19 x: xzxjxxxxxxxxxxxxxxj\n" +
            "11-16 w: kwclzxjjwxlwkcnwkwv\n" +
            "3-11 b: zhhxsgqxqbbg\n" +
            "10-11 q: trbhqqzhdqw\n" +
            "9-13 l: vcvlvqlwrlfvll\n" +
            "7-9 x: xxxxxxxxgx\n" +
            "5-6 n: nnnngnn\n" +
            "2-5 p: pqpppppppqpxp\n" +
            "4-17 z: zxrmzwwxwhqxxmqrv\n" +
            "5-9 v: vvvvvvvvrvvvj\n" +
            "6-7 x: qkhbxxkxs\n" +
            "3-4 d: fcmd\n" +
            "5-9 f: nsnlxstff\n" +
            "6-9 x: hrtzmhrxxbmcc\n" +
            "3-7 w: wwwwwwsww\n" +
            "5-8 g: ngkdxggg\n" +
            "8-13 r: rrrrphrrrrrrrrrrdrt\n" +
            "2-6 f: rckzvzfrnp\n" +
            "4-6 k: bfrpttcfbwmvhgn\n" +
            "7-9 w: wwwwwwswww\n" +
            "13-15 n: nnnnnnnnnnnnnnn\n" +
            "4-8 j: jjjjjjjwjjj\n" +
            "9-11 h: hhhhhhrhhhhhh\n" +
            "4-7 h: thmhwrhss\n" +
            "1-3 d: ddddddddddddd\n" +
            "10-11 c: ckrcxwcdpqc\n" +
            "2-4 g: kgghg\n" +
            "3-12 s: ssssvwssssgqs\n" +
            "2-7 s: sssssszs\n" +
            "2-10 v: wvpbjqxvzsdpgmq\n" +
            "12-15 n: nnnnnnbnqvrkfnn\n" +
            "3-5 w: wlvdw\n" +
            "11-14 t: pfrbxgcrwndttj\n" +
            "6-7 w: qnnwwpfwwhw\n" +
            "7-10 n: nnnvnnhnnx\n" +
            "3-12 c: mmfcwvxqwpcclwlxfx\n" +
            "2-3 p: lgpxpppp\n" +
            "17-19 k: rfxvmnmfzrnktfpckpr\n" +
            "2-9 k: kkkknkkkkkkk\n" +
            "15-16 t: ttjmtttmttttttwt\n" +
            "9-10 r: rrrrrrrrmrrrr\n" +
            "3-4 p: jppppxf\n" +
            "7-8 k: nkqbvkkt\n" +
            "6-8 d: dddddrdddd\n" +
            "6-7 q: czbqdgnc\n" +
            "3-5 p: rxpppsx\n" +
            "4-6 t: thvtwv\n" +
            "2-13 d: dmdddddddddddd\n" +
            "16-18 n: nnnnnnnnnnnnnnnnnnn\n" +
            "11-12 s: ssfsdsmssswssh\n" +
            "3-5 v: kxnvvvmvrvdvvssvvv\n" +
            "5-8 x: nxxxxbxxxzx\n" +
            "3-5 t: ctttftt\n" +
            "5-7 s: hssvsgj\n" +
            "5-8 r: rrrrrrrcrx\n" +
            "1-13 v: vvvvvvvvvvvvpvvvvvv\n" +
            "5-9 h: gxlrhsgswhchfxbwjd\n" +
            "2-4 w: wgwb\n" +
            "6-12 v: pmxnjtfsvvxvv\n" +
            "1-4 n: vnntn\n" +
            "2-3 w: wwww\n" +
            "3-7 f: xmfbmnvnfkkmsd\n" +
            "10-12 x: xxxxxxjgxxxxx\n" +
            "2-3 l: cllvpbtmgzmrfmq\n" +
            "2-4 l: llrlllnlxll\n" +
            "5-10 h: hdhhhzhvtchhh\n" +
            "8-10 q: lhqmdwcfhqngq\n" +
            "1-5 t: twtfvcmktthtjltqvpwc\n" +
            "6-8 s: sxsghtbs\n" +
            "3-4 m: mmmmmmmmmmmmmmmm\n" +
            "16-17 l: rjdpxhtblvllgvwhl\n" +
            "5-13 s: brhsssnfcndsh\n" +
            "7-13 v: swkfswvmkvjbnsgvwp\n" +
            "1-3 k: wlfpzk\n" +
            "2-4 t: tpttt\n" +
            "2-9 t: cntttttcgtttt\n" +
            "5-6 r: rrrrbh\n" +
            "10-12 j: jjjjjjjjjzjjdj";

    static boolean doTheMagic(int minValue, int maxValue, final char character, String password) {
        long count = password.chars().filter(ch -> ch == character).count();

        return minValue <= count && count <= maxValue;
    }

    static boolean doAnotherMagic(int minValue, int maxValue, final char character, String password) {
        return password.charAt(minValue-1) == character && password.charAt(maxValue - 1) != character
                || password.charAt(minValue-1) != character && password.charAt(maxValue - 1) == character ;
    }

    static void generateSolutionForPartOne() {
        String[] strings = input.split("\n");
        Integer counter = 0;
        for (String line :
                strings) {
            String[] subStrings = line.split("\\s");

            //Get min and max value of letters in the text
            String[] minMaxValue = subStrings[0].split("-");
            int minValue = Integer.parseInt(minMaxValue[0]);
            int maxValue = Integer.parseInt(minMaxValue[1]);

            //get the verification letter
            char letter = subStrings[1].charAt(0);

            //get the password
            String password = subStrings[2];
            if (doAnotherMagic(minValue, maxValue, letter, password)) {
                counter++;
            }
        }
        System.out.println(counter);

    }

    public static void main(String[] args) {
        generateSolutionForPartOne();
    }
}
