import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.TreeMap;

public class Day5 {

    static String inputs = "FFBFBBBRLR\n" +
            "BBFFBFFRRR\n" +
            "BFFFFBBRRR\n" +
            "FFBFFBBLRR\n" +
            "FFBFBFBLLL\n" +
            "FFBFFBFLRR\n" +
            "BFFFBBBLLR\n" +
            "FFBFBFFRLR\n" +
            "FFBFFFBRRR\n" +
            "FFBFFFFRRL\n" +
            "BFFBBFFLRL\n" +
            "FFFBFFBLRR\n" +
            "FBBFBFFRLR\n" +
            "BFFFBFBRLR\n" +
            "BFBFFBBRLR\n" +
            "FFBBFBBLRR\n" +
            "BFBBBFBRLR\n" +
            "FFBBBFBRRL\n" +
            "FFBFBBBRRR\n" +
            "BFBBBBFRLL\n" +
            "FBBFFFBRRR\n" +
            "BFFBFBFRRR\n" +
            "FFBFBBBLRL\n" +
            "FBFFFFBLLR\n" +
            "BBFFBFBRLL\n" +
            "FBBBFFBLRL\n" +
            "FBBBFFFRRR\n" +
            "BFBFFBFRLR\n" +
            "BFFFFBBLLL\n" +
            "FBFFBBFRLR\n" +
            "BFBBBBBLLR\n" +
            "FFFFBBFLRR\n" +
            "FBFBFBFRLR\n" +
            "FBFFBFFLRR\n" +
            "FFBFFBFRRR\n" +
            "BFFBFBFRLL\n" +
            "BFFFBBBLRR\n" +
            "FFBBFFFLLR\n" +
            "FBBBFBBLRR\n" +
            "FFBBFBFRRL\n" +
            "BFFBFFBRLL\n" +
            "FBFFFBBLLR\n" +
            "BFFFBFBLRL\n" +
            "FFFBFBBRRL\n" +
            "FBBBFBBRLL\n" +
            "BFFBBBFRLL\n" +
            "FBFFFFBLRR\n" +
            "FFFBBBBLRR\n" +
            "FFBFFBBLLL\n" +
            "FBFBFBBRRL\n" +
            "FFFBFBFRLR\n" +
            "FBBFFFFRRR\n" +
            "BFFFBBBRLR\n" +
            "FBBBBFFLRR\n" +
            "FFFFBBFLLR\n" +
            "BFFBBBFRRR\n" +
            "FBBBFFBRLL\n" +
            "FBBBFBFLLR\n" +
            "FBFBBFFRRL\n" +
            "FFFBBFFLLR\n" +
            "FFBFBFFLRL\n" +
            "BFBBBFFRRL\n" +
            "BFFBFBFRRL\n" +
            "FFFBFBBLLL\n" +
            "BFFBFFBLLR\n" +
            "FBFBBFFLLL\n" +
            "FFBBFBFLRR\n" +
            "FFFBBBFRLR\n" +
            "FBBBFBFRLL\n" +
            "FBBBBBFLRR\n" +
            "FFBFBFBRLR\n" +
            "BBFFFFBRLR\n" +
            "BFFBFBBRRL\n" +
            "FBFFFFBRLL\n" +
            "FFBFBFBLRR\n" +
            "FBBBBFFRRR\n" +
            "FBFBBBFLRL\n" +
            "FBBBFFFLLL\n" +
            "BFBFBFFRLL\n" +
            "FBFFFBFLLR\n" +
            "BFBFFBFLRL\n" +
            "BFBBBFBLRR\n" +
            "FBBFFBBRLR\n" +
            "BFFFBBBRLL\n" +
            "FBFBBBFLLL\n" +
            "BFFFBFBLRR\n" +
            "BFBBBFFRLR\n" +
            "FFBBFFFRLL\n" +
            "FFFBFBFRRL\n" +
            "FBBFBFBLLR\n" +
            "FBFFBFFLRL\n" +
            "FBBFFBBLLR\n" +
            "FBBBFBBRLR\n" +
            "FBBBFBBLLR\n" +
            "FBBFBBBLLL\n" +
            "BFFFFBBRRL\n" +
            "FBBFFBBRRR\n" +
            "BFBFFBBLLR\n" +
            "FFBBBBFLLR\n" +
            "FFBFBFFLRR\n" +
            "BBFFFBFRLL\n" +
            "FFBFBBBLLL\n" +
            "BFFFFBFRRL\n" +
            "FBFBBBBLLL\n" +
            "BFBBFFBLRR\n" +
            "BFBBBFBRLL\n" +
            "FBFFFFFLLL\n" +
            "FBFBBFFLRL\n" +
            "FFFBBFBLRL\n" +
            "BFFFBFBLLR\n" +
            "FBFBFFFRLL\n" +
            "BBFFBFFLLL\n" +
            "FFFFBBFLLL\n" +
            "BFBBFBBLRR\n" +
            "BFBBFBBRLR\n" +
            "BFBFFFBLLL\n" +
            "FBBBBFBRLL\n" +
            "FFBFBBBLRR\n" +
            "FFFBFBBLRL\n" +
            "BFBFFBBRLL\n" +
            "BFBFBBBRLL\n" +
            "FFBFBBBRRL\n" +
            "FFFBBBBRLR\n" +
            "FFBBBBFLLL\n" +
            "FBFBFBFRLL\n" +
            "BFBFBBBLRL\n" +
            "FFBBFFBRLL\n" +
            "BFFBBFBRLR\n" +
            "FFBBBBFLRR\n" +
            "FFFBBBFLLL\n" +
            "FFBFBBFLRL\n" +
            "BFFBBFFLRR\n" +
            "FFFFBBBLLL\n" +
            "BFBFFFFRRL\n" +
            "FBFFBBBRRR\n" +
            "FBBFFBFRRR\n" +
            "BFFFBFFRRR\n" +
            "FFBBBFBRLL\n" +
            "BBFFFBBLLL\n" +
            "FFFFBBBRRR\n" +
            "FFFBBFBRRL\n" +
            "BBFFFBBLRR\n" +
            "FBBFFFFLLR\n" +
            "BFBFBBBRLR\n" +
            "FFBFFBFRLR\n" +
            "BFBFBFBLRR\n" +
            "FBBFFBFLLL\n" +
            "FBFBBFBLLR\n" +
            "FBFFBBFRRR\n" +
            "BFFFBBFRLR\n" +
            "BFFFFFFRRR\n" +
            "FFFBFFFLRR\n" +
            "FBFBBFBRLR\n" +
            "FFFBFBFLRL\n" +
            "FFFBFFBLRL\n" +
            "BFBFBFBRRR\n" +
            "FFFBFFBRRL\n" +
            "FFBBFFBRLR\n" +
            "BFFBBFBLLR\n" +
            "FFBFFFFLLR\n" +
            "FBBBBBFLRL\n" +
            "FBBBBFFLRL\n" +
            "BFBFFBFLRR\n" +
            "FFFBBBBLLL\n" +
            "FFFBBFBLRR\n" +
            "BFBBBFFLLR\n" +
            "FBFBBFFLRR\n" +
            "BBFFFBFRRR\n" +
            "FBFBBFBLRL\n" +
            "FFBBFFFLRL\n" +
            "BFBFBFFLRR\n" +
            "BFBFBFBRLL\n" +
            "FBFBBBFLRR\n" +
            "FBFFFFFLRR\n" +
            "BFFFBBBRRL\n" +
            "BFBBFFBRRR\n" +
            "BBFFFBFLRL\n" +
            "BFFBFFFRLL\n" +
            "BBFFFBFLRR\n" +
            "BFFBFBBRRR\n" +
            "FBFFFBFLRL\n" +
            "FBFBFBBLLR\n" +
            "FFFBBFBRLR\n" +
            "BFBBBFFRRR\n" +
            "FBFBFBFRRL\n" +
            "FBFFBFBLLR\n" +
            "BFFBFBFLRL\n" +
            "FBBBBFBLLL\n" +
            "FFFBFBBLLR\n" +
            "BFBFFFFRLR\n" +
            "FBBBBBBLLL\n" +
            "FBBBBFBLLR\n" +
            "FFBFBBFRLL\n" +
            "BFBBFFFLRL\n" +
            "FFFBFFBLLL\n" +
            "BFBFFFBLRL\n" +
            "FBBBBFFRLL\n" +
            "BFBBFFFRRL\n" +
            "BFBBBBFRRR\n" +
            "BFBBBBFLLL\n" +
            "BFFBFBBLLL\n" +
            "FBFBFFFRRR\n" +
            "BFBBFFFRLL\n" +
            "FBBFBBBRRR\n" +
            "BFFFFFBLRL\n" +
            "FBFFFBFLRR\n" +
            "FBFBFBBLLL\n" +
            "BFBBFFBRLL\n" +
            "BFFBBFFRRL\n" +
            "FBFBFFFLLR\n" +
            "FBFFFBBRRL\n" +
            "BFBFBBFRRL\n" +
            "BBFFFFFLLR\n" +
            "BFBFBFFRRR\n" +
            "FFBFFFFLRL\n" +
            "FBBBFBBLRL\n" +
            "FFBBBFFLRR\n" +
            "FBBBBFBRRL\n" +
            "FFFBBBFRRL\n" +
            "BFBFBFFLLL\n" +
            "BFFBFBFRLR\n" +
            "BFBBFBFRLR\n" +
            "FBFBFBBRLL\n" +
            "FBFFBBBRRL\n" +
            "BBFFFFBLRR\n" +
            "BFFFFFBRLR\n" +
            "FBBFFBFLRL\n" +
            "BFBFFBFRLL\n" +
            "BFFFBBFLRL\n" +
            "FBBBFBFRRR\n" +
            "BBFFFFFLLL\n" +
            "FBFBBFBRLL\n" +
            "BFBFBFBLLL\n" +
            "FBBFFBFRLR\n" +
            "FBBBFBFLRR\n" +
            "FBFFFFFLLR\n" +
            "BBFFBBFLLL\n" +
            "FFBFBBFLRR\n" +
            "FFBBBBFLRL\n" +
            "BFFFFBBLRL\n" +
            "BFFFFFBRRL\n" +
            "FBFFFFBRLR\n" +
            "FFBBFBBRRR\n" +
            "FFBFBBFLLR\n" +
            "FBFBBBBLLR\n" +
            "BFFFBFFLRR\n" +
            "BFFBBBFRRL\n" +
            "FBBBBBBRRL\n" +
            "FBBBBFBRLR\n" +
            "BFBFBBFLLL\n" +
            "BFFBBBFRLR\n" +
            "BFBBFBBRLL\n" +
            "FBBBBBBRLL\n" +
            "FFBBFFFRLR\n" +
            "FFFBBFFRLL\n" +
            "FBFBBBFRLL\n" +
            "FBBFFBFLRR\n" +
            "BFBBFFBRLR\n" +
            "BFFBBFBRRR\n" +
            "FFBFBBFRRL\n" +
            "FFBFBBFLLL\n" +
            "FFFBBFBLLL\n" +
            "FBFFFBFRLL\n" +
            "FFBBBFFRLR\n" +
            "FFFBFBBLRR\n" +
            "FBBFFBFLLR\n" +
            "BBFFFBFLLL\n" +
            "BBFFFBBRLR\n" +
            "FFBBBFFLRL\n" +
            "FBFBBFBRRR\n" +
            "BFFFBBFLRR\n" +
            "FBBBFFFRLL\n" +
            "BFFBFFBRRL\n" +
            "FBBBBBBLRR\n" +
            "BFFFBFFRRL\n" +
            "FFBFBBBRLL\n" +
            "FBFBBFFLLR\n" +
            "BFFFBBBLLL\n" +
            "BFBFFFFLLR\n" +
            "FBBBBBBLLR\n" +
            "FFBBFBFRRR\n" +
            "FBFBFBFLLL\n" +
            "BFBFBFBLLR\n" +
            "FFBBFBBLRL\n" +
            "FFFFBBBLRR\n" +
            "BFFBFBBRLR\n" +
            "BFFBBBBRRL\n" +
            "FBFFBFFLLL\n" +
            "BFBBBBBRRR\n" +
            "BFBFFFFLRL\n" +
            "FFFBBBBRLL\n" +
            "BFFFBFFLLR\n" +
            "FBBFBFFLRR\n" +
            "BFBFFBFLLR\n" +
            "FBBBBFBRRR\n" +
            "FFBFFBBRRR\n" +
            "FFBFFFFRRR\n" +
            "FBBFBFBLRR\n" +
            "BFBFBBFRRR\n" +
            "FBFFFBFRRR\n" +
            "FBFFBFFRRR\n" +
            "BFFFBBFLLL\n" +
            "BFBFBBFLRR\n" +
            "BFFBFFFRLR\n" +
            "FFFBFFBLLR\n" +
            "FFFBFFFLLR\n" +
            "FBBBBBFRRL\n" +
            "FBBFBBFRRL\n" +
            "BFFBFFBRLR\n" +
            "BBFFBFFRLR\n" +
            "FFBBFFFRRR\n" +
            "FBFFFFFRRR\n" +
            "BBFFFBBLLR\n" +
            "BBFFBBFLRL\n" +
            "FFBBBBBLLR\n" +
            "FFBFBBFRLR\n" +
            "BFFBFFBRRR\n" +
            "BFBFFFBRLL\n" +
            "FFBBBBFRLR\n" +
            "BFFFFFFLRL\n" +
            "BFBBFBBRRL\n" +
            "BFFBBFBLRR\n" +
            "FFFBBBFLRL\n" +
            "BFBBFBBRRR\n" +
            "FFBBFFFLLL\n" +
            "FFFBBFFRLR\n" +
            "FBFBFFBLRR\n" +
            "BFFFFBFRRR\n" +
            "BBFFBFBLLL\n" +
            "BFFFFBFLRL\n" +
            "BFFBBBFLLR\n" +
            "BFFFBFFRLR\n" +
            "FBFBBBBRLL\n" +
            "BBFFBFFRLL\n" +
            "FBFFBBFLRL\n" +
            "FFBFFBBRRL\n" +
            "BFFFFBBRLL\n" +
            "FFFFBBBLRL\n" +
            "FFBFBFBLLR\n" +
            "BFBFBBBLLL\n" +
            "FBBFFBBLRR\n" +
            "FFBBBBFRRR\n" +
            "FFBBBFFLLL\n" +
            "BFBBBFBLLR\n" +
            "FFFFBBFRRR\n" +
            "BFFBBBBRRR\n" +
            "FFBBFFBLLL\n" +
            "FBFFFFFLRL\n" +
            "FBFBBBFLLR\n" +
            "FFBBFFFLRR\n" +
            "FBFBFBFLRR\n" +
            "BFFBFBBLRL\n" +
            "FBFFFFBLLL\n" +
            "FFBBBBBRRL\n" +
            "FBBBBFFLLL\n" +
            "BBFFFFBLLL\n" +
            "BFFBBFBRRL\n" +
            "FFBBBFFLLR\n" +
            "FBBFBFBRRR\n" +
            "BBFFFBBRRR\n" +
            "FBFBFFBRLL\n" +
            "FBFFBFBLRR\n" +
            "BFBFFBBRRL\n" +
            "FBBFBBFLRR\n" +
            "BBFFFFBLRL\n" +
            "BFFBBBBRLR\n" +
            "BFBFFBBRRR\n" +
            "FBBFFFBRLR\n" +
            "FBBFBBBLRL\n" +
            "FBFBFBFRRR\n" +
            "FFBFFFBRLR\n" +
            "FFBBFBFLRL\n" +
            "FFBBBBFRRL\n" +
            "FFBBBFBLRR\n" +
            "BFFBBFFLLR\n" +
            "FFFFBBBRLL\n" +
            "BFBBFBBLLR\n" +
            "BBFFFFBRLL\n" +
            "FBBFFFFLRR\n" +
            "BFFBFBFLLR\n" +
            "FBBBFBFLRL\n" +
            "FBBFFFFLLL\n" +
            "BFFBFFFLRR\n" +
            "BFBBFBFLRR\n" +
            "BFFBFBBRLL\n" +
            "FBFFBBBLRL\n" +
            "FBBBFFBLLL\n" +
            "FBBBFFFLRL\n" +
            "BFFBBBBLLL\n" +
            "BFFFBFFLLL\n" +
            "FFFBFFBRRR\n" +
            "FFBFFFBLRL\n" +
            "FBBFBBBLRR\n" +
            "FFFBBFBRRR\n" +
            "FBBFBFFLLL\n" +
            "BFBFBBFLRL\n" +
            "BFFBFFFRRL\n" +
            "BFBFBBBLRR\n" +
            "FFBFFBBRLL\n" +
            "FFBFBFFLLR\n" +
            "BFBBBBBRRL\n" +
            "FBFFBFFRLR\n" +
            "BBFFBFBLRL\n" +
            "FFFBBFFLRR\n" +
            "BBFFBBFLLR\n" +
            "FFFBBBBRRR\n" +
            "FFBFFBFLLR\n" +
            "BFFFFBFRLR\n" +
            "FFBFFFFLRR\n" +
            "BBFFFFFRLR\n" +
            "FBFBBBBLRL\n" +
            "FBFFBBFRRL\n" +
            "BFBBFBFRRR\n" +
            "FBBBBFFLLR\n" +
            "FFBBBFFRRR\n" +
            "FBBFBFBRRL\n" +
            "BFBBFBBLLL\n" +
            "BBFFFBBRLL\n" +
            "FBBFBFFRRL\n" +
            "FBBBBBFLLL\n" +
            "BFBBBFFLRR\n" +
            "BFFFFFFRRL\n" +
            "BBFFFBFRLR\n" +
            "BFBFFFBLRR\n" +
            "FBFBFFFLRR\n" +
            "BBFFFBBLRL\n" +
            "BFFFFBBRLR\n" +
            "BFFBFBBLRR\n" +
            "BFBFFFBRLR\n" +
            "BFFFFBBLRR\n" +
            "BBFFFFBRRL\n" +
            "BFBBBFBRRR\n" +
            "BFBBBBBLRL\n" +
            "FFFBBBFLRR\n" +
            "BFFBBFFRLL\n" +
            "FBFFBFBRRR\n" +
            "FFFBBFFLLL\n" +
            "FFBFFBFRRL\n" +
            "FBFFBFFRLL\n" +
            "BFBBBFFLLL\n" +
            "BFFFBFBRRL\n" +
            "FFFBFFFRRL\n" +
            "FFFBFBFLLL\n" +
            "FFFBBBBRRL\n" +
            "BFBBFFBRRL\n" +
            "BFBFFBFLLL\n" +
            "BBFFFBFRRL\n" +
            "BFBFBFFRLR\n" +
            "FFFBFBBRLR\n" +
            "BFBFBFBLRL\n" +
            "BFFBFFFLLR\n" +
            "FBFBBBFRRL\n" +
            "FBFBBBBRLR\n" +
            "BFFBBBBLRL\n" +
            "BFBBFBFLLL\n" +
            "FFFBFFBRLL\n" +
            "FBBFFFBLRR\n" +
            "FFFFBBFRLR\n" +
            "BFBFFFFRRR\n" +
            "BFBBFBFLRL\n" +
            "FFBFBFFRRR\n" +
            "BFBBBBBRLL\n" +
            "FBFFFFFRLR\n" +
            "FBFBFFBLLL\n" +
            "FFBBFFBRRR\n" +
            "FFFBBBFRRR\n" +
            "FBFFBBFLLR\n" +
            "BFBBFFBLLL\n" +
            "BFBBFFFRRR\n" +
            "FBFBBFFRLL\n" +
            "FFBBBBBLRR\n" +
            "FBFBFBBLRR\n" +
            "FBFFFBFRRL\n" +
            "FBBFFFBRRL\n" +
            "BFFBBBBLLR\n" +
            "BFBBFFFRLR\n" +
            "FBBBFFFLRR\n" +
            "FBBFBBBRLR\n" +
            "FFFBFBFLLR\n" +
            "FFBFBFBRRR\n" +
            "BFBFBBBRRL\n" +
            "FBFFBFFLLR\n" +
            "FFFBFFBRLR\n" +
            "BFBFBBFLLR\n" +
            "FBBFFFBLLL\n" +
            "FBFFBFBRLL\n" +
            "BFFFBBFRRL\n" +
            "FBBBBBFRRR\n" +
            "BBFFFFFRRL\n" +
            "BFBFFFFLLL\n" +
            "FBFFFFBRRR\n" +
            "BFFFFFFRLR\n" +
            "BFFBFFBLRL\n" +
            "BFBBFBFRRL\n" +
            "BFBBFFFLLL\n" +
            "FFBBBFBRLR\n" +
            "FFFBFBBRLL\n" +
            "FBFFFBBLRR\n" +
            "BFFFFFBRRR\n" +
            "BBFFBFBRRL\n" +
            "FFFFBBFRLL\n" +
            "BFBBBBFRLR\n" +
            "BFBBBFBRRL\n" +
            "BFBFBFBRLR\n" +
            "FFBFBFBLRL\n" +
            "BFBFFFFRLL\n" +
            "FBFFBBBRLR\n" +
            "FBFBFFBLLR\n" +
            "FFBFFFBLLR\n" +
            "FBFBBBBRRR\n" +
            "FFFBBBFLLR\n" +
            "BBFFFFFRRR\n" +
            "FBBFBBFRRR\n" +
            "FBBFBBBRLL\n" +
            "BFFFFFBLLR\n" +
            "BFFFBBFRRR\n" +
            "FBFFFFBLRL\n" +
            "FFFBFBFRRR\n" +
            "FFBFFFBRLL\n" +
            "FBBBBBFLLR\n" +
            "FFBFFFBLLL\n" +
            "BFFFFBBLLR\n" +
            "FBFFBFBLRL\n" +
            "FFBBFFBRRL\n" +
            "BFFBFFBLLL\n" +
            "FBBBFBBRRR\n" +
            "BFFBBFBLLL\n" +
            "FBFBBBFRLR\n" +
            "FFBBFBBLLL\n" +
            "FFBBFFBLRR\n" +
            "BFFFFFFLRR\n" +
            "FFBFFBBRLR\n" +
            "FBBBBBFRLL\n" +
            "FFBBFFBLLR\n" +
            "FBFFBBBLLR\n" +
            "FBFBFFBRRL\n" +
            "BFFBBBFLLL\n" +
            "FFBFFFFRLR\n" +
            "FBFBFBBRLR\n" +
            "FBBFFFBLRL\n" +
            "FFBFBFBRRL\n" +
            "FBFFFBFRLR\n" +
            "FBBBBBBLRL\n" +
            "FFFFBBBRRL\n" +
            "BFBBBBFLLR\n" +
            "BBFFBFBRLR\n" +
            "FBBBBFFRLR\n" +
            "BFFFFFFRLL\n" +
            "FBBFFBBLRL\n" +
            "FBFBFBBLRL\n" +
            "FBFBFBBRRR\n" +
            "BFBBBBFRRL\n" +
            "BFBBBBBRLR\n" +
            "FFFBBFBRLL\n" +
            "FBBFFBBRLL\n" +
            "BFFFFFFLLL\n" +
            "FBBBFBFLLL\n" +
            "FBBFBBFLRL\n" +
            "FFBBBBBRRR\n" +
            "BFBFFBBLRL\n" +
            "BFFBFBBLLR\n" +
            "FBBBBFBLRR\n" +
            "BFBBFFBLRL\n" +
            "BBFFFFBLLR\n" +
            "BFFFBFBRLL\n" +
            "FBBBBFBLRL\n" +
            "BFBFBFFLLR\n" +
            "FBBBFBBLLL\n" +
            "FBBFFBFRRL\n" +
            "BBFFBFFLRR\n" +
            "FBFBFBFLLR\n" +
            "FBBFBBFLLL\n" +
            "FBFFBFFRRL\n" +
            "FFBBBBBRLR\n" +
            "FBBBFFBLRR\n" +
            "FBBBBBFRLR\n" +
            "FBFBBBBRRL\n" +
            "BBFFFBFLLR\n" +
            "FBFBBFBRRL\n" +
            "BFFFFFBLRR\n" +
            "FFFBFFFLLL\n" +
            "FBFBFFFLRL\n" +
            "FFBFFBFLRL\n" +
            "BFBFFBFRRR\n" +
            "FBFBFFBLRL\n" +
            "FFBFFBBLRL\n" +
            "FFBBFBFLLR\n" +
            "FBFBBFFRLR\n" +
            "FFBFBFFRLL\n" +
            "BFBFFBFRRL\n" +
            "BFFFFFBRLL\n" +
            "BFBBBFFLRL\n" +
            "BBFFBFFLLR\n" +
            "BFFFBBFLLR\n" +
            "BFFBBBFLRR\n" +
            "FBBFFFFRRL\n" +
            "FFBBBFBLLR\n" +
            "BFBBBFBLLL\n" +
            "BFFFFFFLLR\n" +
            "FBBFBBFLLR\n" +
            "FBFBBFBLRR\n" +
            "FFBFBBFRRR\n" +
            "BFFBBFFRLR\n" +
            "BFFBBBFLRL\n" +
            "FBFFBFBRLR\n" +
            "BFBBFFBLLR\n" +
            "BFBFFFFLRR\n" +
            "FFBBBBBRLL\n" +
            "FBBBFBBRRL\n" +
            "BFFBBFFRRR\n" +
            "FBFFBBBRLL\n" +
            "FFBFFFFRLL\n" +
            "BFBFBFBRRL\n" +
            "FBBFFBFRLL\n" +
            "BFFFBFFRLL\n" +
            "BFBBBBBLLL\n" +
            "FBBBFFBLLR\n" +
            "FFFBFBFLRR\n" +
            "FFFBBFFRRL\n" +
            "FFBBBFBLRL\n" +
            "BFFBFBFLLL\n" +
            "FFBBBFFRLL\n" +
            "FFBFFBFLLL\n" +
            "FBBBFBFRLR\n" +
            "FFBBFBFLLL\n" +
            "BFBBFFFLLR\n" +
            "FBBBFFFRLR\n" +
            "FBFFFFBRRL\n" +
            "FFFBFBBRRR\n" +
            "FBFFBBFLRR\n" +
            "BBFFFFFRLL\n" +
            "FBFFBBBLRR\n" +
            "FBFBFFBRRR\n" +
            "FBFFFFFRLL\n" +
            "FFBFFFBRRL\n" +
            "FFFFBBFLRL\n" +
            "BFBBFBBLRL\n" +
            "FFBFFBBLLR\n" +
            "BFBFBBBLLR\n" +
            "FFBBBFBLLL\n" +
            "BBFFBFBLLR\n" +
            "FFFBFFFLRL\n" +
            "FBFFFBBLRL\n" +
            "FBFFFBBRLL\n" +
            "BFFFBFFLRL\n" +
            "FBBBBBBRRR\n" +
            "FBFFFBBLLL\n" +
            "FFFBFFFRLR\n" +
            "FBBFBBBRRL\n" +
            "BFFBBFBRLL\n" +
            "FFFBBFBLLR\n" +
            "FBBBFFBRRL\n" +
            "BFBFBBFRLR\n" +
            "FBFFBFBLLL\n" +
            "BFBFFFBLLR\n" +
            "FFFBBBFRLL\n" +
            "FBFFBBFLLL\n" +
            "FBBBFFFLLR\n" +
            "FBBBFBFRRL\n" +
            "BFBFFFBRRR\n" +
            "BFBFBBFRLL\n" +
            "BFFBFFFLRL\n" +
            "BFFBBBBRLL\n" +
            "BBFFBFFRRL\n" +
            "BFBFBFFRRL\n" +
            "FBBFBBFRLL\n" +
            "FFFBBBBLLR\n" +
            "BFFBFFFRRR\n" +
            "FFFFBBBLLR\n" +
            "BFFBBFBLRL\n" +
            "FBBFFFFLRL\n" +
            "FBBFBFBLRL\n" +
            "FBFFFBFLLL\n" +
            "BFFFFBFLRR\n" +
            "FBFFBBFRLL\n" +
            "FFBBFBBRLR\n" +
            "BFBBBBFLRL\n" +
            "FFFBFBFRLL\n" +
            "FBBFFFBRLL\n" +
            "FFBFFBFRLL\n" +
            "BFFBFBFLRR\n" +
            "FFFFBBBRLR\n" +
            "BFBBFFFLRR\n" +
            "FBFBFBFLRL\n" +
            "FFBBBBFRLL\n" +
            "BBFFBFBLRR\n" +
            "FFBBBFBRRR\n" +
            "BFBBBFBLRL\n" +
            "BFFFFFBLLL\n" +
            "BFFBFFFLLL\n" +
            "FBBBBFFRRL\n" +
            "FFBBFFFRRL\n" +
            "FBBFFBBLLL\n" +
            "BBFFBFBRRR\n" +
            "FBFBFFFRLR\n" +
            "FFBFFFBLRR\n" +
            "FBFBBFBLLL\n" +
            "BFFBBBBLRR\n" +
            "BFFBBFFLLL\n" +
            "FFBFFFFLLL\n" +
            "BBFFFFFLRR\n" +
            "FBBFBFBRLR\n" +
            "BBFFFBBRRL\n" +
            "BFFFFBFLLR\n" +
            "FBBFBFFRLL\n" +
            "BFFBFFBLRR\n" +
            "FFFBFFFRRR\n" +
            "FBFFBFBRRL\n" +
            "FBBFBFFRRR\n" +
            "BFBBBBFLRR\n" +
            "FBBBFFFRRL\n" +
            "FFBBFBBLLR\n" +
            "FFFFBBFRRL\n" +
            "FFBBFBBRRL\n" +
            "BFFFBBBLRL\n" +
            "FBBBFFBRRR\n" +
            "FBBFBFBLLL\n" +
            "FBFBFFBRLR\n" +
            "BFFFBBFRLL\n" +
            "BBFFFFFLRL\n" +
            "BFFFBFBLLL\n" +
            "FFBFBFFRRL\n" +
            "FBFFFBBRRR\n" +
            "FFBBFFBLRL\n" +
            "FBFBBBFRRR\n" +
            "FFBBFBBRLL\n" +
            "FFBBBBBLLL\n" +
            "FFBFBFFLLL\n" +
            "BFBFFBBLLL\n" +
            "FFFBBBBLRL\n" +
            "BBFFBFFLRL\n" +
            "FBFFFFFRRL\n" +
            "FFBFBBBLLR\n" +
            "FBBFFFFRLR\n" +
            "FFBBBFFRRL\n" +
            "FBBFBFFLLR\n" +
            "FBFBFFFRRL\n" +
            "FBBFFFFRLL\n" +
            "BFBBBFFRLL\n" +
            "BBFFFFBRRR\n" +
            "BFBFBBBRRR\n" +
            "FBFFFBBRLR\n" +
            "BFFFFBFRLL\n" +
            "FFBFBFBRLL\n" +
            "FBBFBFBRLL\n" +
            "FBBFBBFRLR\n" +
            "FFFBFFFRLL\n" +
            "BFBBFBFRLL\n" +
            "FBBBFFBRLR\n" +
            "FFFBBFFRRR\n" +
            "FBBFFFBLLR\n" +
            "FBBBBBBRLR\n" +
            "FFBBBBBLRL\n" +
            "FBBFBFFLRL\n" +
            "BFBFFFBRRL\n" +
            "FBFBFFFLLL\n" +
            "FFBBFBFRLL\n" +
            "BFBFFBBLRR\n" +
            "FBFFBBBLLL\n" +
            "FBFBBFFRRR\n" +
            "BFFFBBBRRR\n" +
            "BFBBBBBLRR\n" +
            "FBBFBBBLLR\n" +
            "FFFBBFFLRL\n" +
            "FBBFFBBRRL\n" +
            "FFBBFBFRLR\n" +
            "BFBFBFFLRL\n" +
            "BFBBFBFLLR\n" +
            "FBFBBBBLRR\n" +
            "BFFFFBFLLL";

    static ArrayList<Integer> listOfSeatIds = new ArrayList<>();

    static void solutionPartOne(String input) {
        int minRow;
        int maxRow;
        int minColumn;
        int maxColumn;
        int rowsLength = 128;
        int columnsLength = 8;

            minRow = 1;
            maxRow = 128;
            minColumn = 1;
            maxColumn = 8;

            for (int x = 0; x < input.length(); x++) {
                switch (String.valueOf(input.charAt(x))) {
                    case "B":
                        rowsLength = rowsLength/2;
                        minRow = maxRow - rowsLength;
                        break;

                    case "F":
                        rowsLength = rowsLength/2;
                        maxRow = maxRow - rowsLength;
                        break;

                    case "L":
                        columnsLength = columnsLength/2;
                        maxColumn = maxColumn - columnsLength;
                    break;

                    case  "R":
                        columnsLength = columnsLength/2;
                        minColumn = minColumn + columnsLength;
                    break;
                }
                System.out.println("current maxRow: " + maxRow + " and minRow: " + minRow );
                System.out.println("current max Column" + maxColumn + " min column" + minColumn);
            }
            System.out.println("final maxRow: " + maxRow + " and minRow: " + minRow );
            System.out.println("final max Column" + maxColumn + " min column" + minColumn);

            /*if ((minRow*8) + minColumn == 177) {
                System.out.println("WTF");
            }*/
            listOfSeatIds.add((minRow*8) + minColumn);
        }


    public static void main(String[] args) {
        String[] arrayOfInputs = Helper.convertInputToArray(inputs);

        for (String singleInput :
                arrayOfInputs) {
            solutionPartOne(singleInput);
        }
        Collections.sort(listOfSeatIds);
        System.out.println(listOfSeatIds.get(listOfSeatIds.size()-1));

        int count = listOfSeatIds.get(0);
        for (Integer integer: listOfSeatIds) {
            if (integer !=count ) {
                System.out.println("Missing seatID:" + count);
                count++;
            } count++;
        }
    }
}
